### ISSUE TITLE
Create an own clustering algorithm

### ISSUE THREAD

**Issue by indyfree** [indyfree/tailor#28]
Steps:
- [x] Develop clustering algorithm
- [x] Implement parameter for the cluster size
- [x] Make it possible to cluster with any number of features
- [x] Optimize clustering with statistical methods like *Principal Component Analysis* or *Similarity Measure* 

*Make sure the program code is comprehensible and efficient*.
